platform :ios, '13.0'

target 'Example' do
  use_frameworks!

  # MercadoPago CoreMethods SDK
  pod 'MercadoPagoSDKCoreMethods', :path => '../'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13'
      other_swift_flags = config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)']
      preprocessor_macros = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      framework_search_paths = config.build_settings['FRAMEWORK_SEARCH_PATHS'] ||= ['$(inherited)']
      if ["MDS"].include?(config.name)
        preprocessor_macros << 'DEBUG=1'
        other_swift_flags << '-DDEBUG'
        framework_search_paths << "${PODS_CONFIGURATION_BUILD_DIR}/DeveloperMode"
      end
    end
  end
end
