//
//  ThreeDSAuthRequestParameters.swift
//  MercadoPagoSDK
//
//  Created by Guilherme Prata Costa on 26/08/25.
//

import Foundation

/// Authentication request parameters required for 3D Secure server communication.
///
/// This structure contains all the necessary parameters generated by the 3DS SDK
/// that must be sent to your backend for 3D Secure server authentication.
/// Your backend will use these parameters to communicate with the 3DS server
/// and determine if a challenge is required.
///
struct MPThreeDSAuthRequestParametersBody: Sendable, Codable{
    /// SDK App ID that identifies the 3DS SDK.
    let sdkAppId: String
    
    /// Encrypted device information collected by the 3DS SDK.
    let deviceData: String
    
    /// SDK ephemeral public key for secure communication.
    let sdkEphemeralPublicKey: String
    
    /// Unique reference number for this SDK instance.
    let sdkReferenceNumber: String
    
    /// Unique transaction ID generated by the SDK.
    let sdkTransactionId: String
    
    /// Token of card
    var token: String = ""
}


extension MPThreeDSAuthRequestParametersBody {
    /// Converts the `MPThreeDSAuthRequestParametersBody` data to JSON format for use in a request body.
    ///
    /// - Returns: A `Data` object representing the post data in JSON format, or `nil` if the conversion fails.
    func toJSONData() -> Data? {
        var jsonObject: [String: Any] = [
            "sdk_app_id": sdkAppId,
            "device_data": deviceData,
            "sdk_ephemeral_public_key": sdkEphemeralPublicKey,
            "sdk_reference_number": sdkReferenceNumber,
            "sdk_transaction_id": sdkTransactionId,
            "token": token
        ]

        return try? JSONSerialization.data(withJSONObject: jsonObject, options: [])
    }
}
