version: 2.1

orbs:
  macos: circleci/macos@2.5.2

executors:
  default:
    macos:
      xcode: 16.0

commands:
  setup_environment:
    steps:
      - macos/install-rosetta
      - run:
          name: Install Dependencies
          command: make setup

jobs:
  build-and-test:
    executor: default
    steps:
      - checkout
      - setup_environment
      - run:
          name: Run SwiftLint
          command: swiftlint
      - run:
          name: Run SwiftFormat
          command: make format
      - run:
          name: Execute Tests and Coverage
          command: bundle exec fastlane test
      - store_artifacts:
          path: fastlane/xcov_output
          destination: code-coverage
      - persist_to_workspace:
          root: .
          paths:
            - .
            - vendor/bundle

  snapshot-tests:
    executor: default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Snapshot Tests
          command: bundle exec fastlane snapshot_tests

  release:
    executor: default
    steps:
      - checkout
      - setup_environment

      - run:
          name: Authenticate GitHub CLI
          command: echo "$GH_TOKEN" | gh auth login --with-token

      - run:
          name: Set CocoaPods Trunk Token
          command: |
            mkdir -p ~/.netrc
            echo "machine trunk.cocoapods.org" >> ~/.netrc
            echo "  login $COCOAPODS_TRUNK_TOKEN" >> ~/.netrc

      - run:
          name: Extract version from MPSDKVersion.swift
          command: |
            VERSION=$(grep -E 'static let version = "' Sources/**/MPSDKVersion.swift | sed -E 's/.*"([0-9.]+)".*/\1/')
            echo "export VERSION=$VERSION" >> $BASH_ENV

      - run:
          name: Run Release Script
          command: |
            source $BASH_ENV
            chmod +x scripts/*.sh
            ./scripts/release-sdk.sh "$VERSION"

workflows:
  version: 2

  build-test:
    jobs:
      - build-and-test
      - snapshot-tests:
          requires:
            - build-and-test

  release-after-merge:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
            paths:
              only:
                - Sources/**/MPSDKVersion.swift
                - "*.podspec"
