version: 2.1

executors:
  ios-executor:
    macos:
      xcode: "16.0.0"

jobs:
  build-and-test:
    executor: ios-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            make setup
      - run:
          name: Run SwiftLint
          command: swiftlint
      - run:
          name: Run SwiftFormat
          command: make format
      - run:
          name: Install xcbeautify
          command: brew install xcbeautify
      - run:
          name: Test
          command: |
            xcodebuild test \
              -scheme MercadoPagoSDK-iOS \
              -sdk iphonesimulator \
              -destination 'platform=iOS Simulator,name=iPhone 16' \
              -enableCodeCoverage YES | xcbeautify
            xcrun xccov view --report build/Logs/Test/*.xcresult --only-targets | \
            awk '/"lineCoverage"/ { coverage = $2 * 100; exit } END { if (coverage < 80) { print "Coverage: " coverage "% - Below minimum 80% requirement"; exit 1 } else { print "Coverage: " coverage "% - Passed" } }'


workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test